## setup for various models
model: ['ecmwf']  # seasonal forecast model
version: ['51']  # and version thereof; pertains to <model> loop indicated with <mm> below
n_mem: [25]  # number of considered hindcast members, pertains to <model> loop. For instance, ECMWF51 has 25 hindcast and 51 forecast members so <n_mem = 25> should be set if hindcasts and forecasts are combined in the skill evaluation. The first n_mem members are selected.
n_lead: [8]  # considered lead-time in months, pertains to <model> loop indicated with <mm> below, CMCC 3.5 hindcasts provide 183 forecast days, SEAS5.1 provide 215, ECCC provide 214

# details example file per model that is available on your file system; the example file must be for the base variables as provided by Jaime, i.e. no climate indices are permitted
template_init: ['199910']  # single init from the hindcast period, expressed as YYYYMM known to be availble, this is to extract the dimensions of the netCDF file for the specific model; it is necessary to set <base_init> because entire hindcast months will be missing for newly introduced models
template_var: ['FD-C4']  # variable for that single init, the file for that variable must be formated by Predictia
template_file_start: ['seasonal-original-single-levels_derived']
template_lon: ['lon']
template_lat: ['lat']

# fixed parameters not passing through loops
imonth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]  # month the forecasts are initialized on, 1 refers to the January 1st, 2 to Febrary 1st etc.

# set MEDCOF domain
domain: 'Canarias'  # spatial domain the model data is available on. So far, this is just a label used to find the input files and name the output files.
save_corrected_files: 'no'  # overwrite input nc files with un expected units with newly generated corrected files

path:
  lustre:
    home: '/lustre/gmeteo/PTICLIMA'
    rundir: '/lustre/gmeteo/PTICLIMA/Scripts/SBrands/pyPTIclima/pySeasonal'
    path_gcm_base: '/lustre/gmeteo/PTICLIMA/DATA/SEASONAL/seasonal-original-single-levels_derived'  # head directory of the source files
    path_gcm_base_derived: '/lustre/gmeteo/PTICLIMA/DATA/SEASONAL/seasonal-original-single-levels_derived'  # head directory of the source files
    path_gcm_base_masked: '/lustre/gmeteo/PTICLIMA/DATA/SEASONAL/seasonal-original-single-levels_derived'  # head directory of the source files
    savepath_base: '/lustre/gmeteo/PTICLIMA/Results/seasonal/gcm/aggregated'  # Directory of the output files generated by this script
    FLAGDIR: '/lustre/gmeteo/PTICLIMA/Scripts/SBrands/pyPTIclima/pySeasonal/FLAG/aggregate_hindcast'

model_settings:
  ecmwf51:
    variables: ['FD-C4','SU-C4','TR-C4']
    variables_nc: ['FD','SU','TR']
    variables_new: ['FD-C4','SU-C4','TR-C4']
    time_name: ['time','time','time']
    lon_name: ['lon','lon','lon']
    lat_name: ['lat','lat','lat']
    file_start: ['seasonal-original-single-levels_derived','seasonal-original-single-levels_derived','seasonal-original-single-levels_derived']
    years: [1981, 2023]