---

obs: 'era5' #name of the observational / reanalysis dataset that will be regridded: 'era5', 'PTI-grid-v2'
agg_src: 'mon' #'day' or 'mon': temporal aggregation of the observational input files, pertains to the <obs> loop indicated with <oo> below
startyear_file: 1981 #start year of the obs file as indicated in filename
endyear_file: 2022 #corresponding end year
variables: ['pvpot','SPEI-3','fwi'] #variables to be regridded
variables_nc: ['pvpot','SPEI-3','FWI'] #variable names with the netCDF file
years: [1981,2022] #years to be regridded

domain: 'medcof' #spatial domain the model data is available on. So far, this is just a label used in the output filename.
resolution: '1degree' #resolution shortcut used in the input variable names

grid_name: 'ecmwf51' #here used as label to save the output netcdf file: ecmwf51 for 1 degree datasets, PTI-grid-v2 for downscaled datasets
int_method: 'conservative_normed' #here used as label to save the output netcdf file, ask Adri if this method was used, 'conservative_normed' or 'upscaled'

paths:
  lustre:
    home: '/lustre/gmeteo/PTICLIMA'
    path_obs_base: '/lustre/gmeteo/PTICLIMA/DATA/REANALYSIS' #base path upon which the final path to the obs data is constructed
    savepath_base: '/lustre/gmeteo/PTICLIMA/Results/seasonal/obs/regridded_test' #This is the common directory for regridded monthly observations; what is placed here will be processed by get_skill_season.py
    rundir: '/lustre/gmeteo/PTICLIMA/Scripts/SBrands/pyPTIclima/pySeasonal' #The run directory